CREATE TABLE SampleTable (
    tagname VARCHAR(50),
    description TEXT,
    short_description VARCHAR(255),
    unit VARCHAR(10),
    path TEXT,
    aggregation VARCHAR(50),
    site VARCHAR(50),
    type VARCHAR(50),
    manufacture VARCHAR(100),
    model_number VARCHAR(100),
    calculated_flow VARCHAR(3),
    water_use VARCHAR(3),
    water_model VARCHAR(3),
    thermal_model VARCHAR(3),
    operations_all VARCHAR(3),
    operations_water VARCHAR(3),
    operations_wastewater VARCHAR(3),
    regulation_water VARCHAR(3),
    regulation_wastewater VARCHAR(3),
    maintenance VARCHAR(3),
    Health_and_Safety VARCHAR(3),
    Building_Condition VARCHAR(3),
    Placeholder_1 VARCHAR(3),
    Placeholder_2 VARCHAR(3),
    Placeholder_3 VARCHAR(3),
    Placeholder_4 VARCHAR(3)
);